const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
 const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge', headless: true });
 try {
 const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
 await context.addInitScript(() => { localStorage.setItem('onebite_token', 'test-only'); localStorage.setItem('onebite_user', JSON.stringify({ name: 'Test staff', role: 'staff' })); });
 const { normalizeBusinessRecord, normalizeBuyer } = await import('../src/lib/business.mjs');
 const records = [], buyers = [];
 await context.route('**/api/**', async route => {
   const request = route.request(); const url = new URL(request.url()); let data = {};
   if (url.pathname === '/api/business') {
     if (request.method() === 'GET') data = { records, buyers };
     else { const body = request.postDataJSON(); const entry = { ...(body.kind === 'buyer' ? normalizeBuyer(body.record) : normalizeBusinessRecord(body.record)), id: body.id, revision: body.revision + 1 }; const list = body.kind === 'buyer' ? buyers : records; const old = list.findIndex(r => r.id === entry.id); if (old >= 0) list.splice(old, 1); list.push(entry); data = { record: entry }; }
   } else if (url.pathname === '/api/products') data = { products: [{ id: 'choc', name: 'Chocolate' }, { id: 'matcha', name: 'Matcha' }] };
   else if (url.pathname === '/api/orders') data = { orders: [] };
   else if (url.pathname === '/api/dashboard/stats') data = { stats: { pendingOrders: 0, acceptedOrders: 0, recentOrders: [], unavailableProducts: [] } };
   else throw new Error('Unexpected API: ' + url.pathname);
   await route.fulfill({ json: data });
 });
 const page = await context.newPage(); const errors = []; page.on('pageerror', error => errors.push(error.message));
 await page.goto('http://localhost:3010/staff/booth');
 await page.getByRole('button', { name: 'Add booth day' }).click();
 await page.getByLabel('Booth name / location').fill('Sunday market');
 await page.getByLabel('Flavour', { exact: true }).fill('Chocolate');
 await page.getByLabel('Prepared (pcs)', { exact: true }).fill('100');
 await page.getByLabel('Sold (pcs)', { exact: true }).fill('70');
 await page.getByLabel('Samples / waste', { exact: true }).fill('5');
 await page.getByLabel('RM / piece', { exact: true }).fill('2.50');
 await page.getByRole('button', { name: '+ Add expense' }).click();
 await page.getByLabel('Expense description').fill('Booth fee');
 await page.getByLabel('Amount (RM)', { exact: true }).fill('40');
 fs.mkdirSync('artifacts/staff-checks', { recursive: true });
 await page.screenshot({ path: 'artifacts/staff-checks/booth-desktop.png', fullPage: true });
 await page.getByRole('button', { name: 'Save record', exact: true }).click();
 await page.getByText('Record saved.', { exact: true }).waitFor();
 assert.equal(records[0].sales, 175); assert.equal(records[0].items[0].leftover, 25);
 await page.getByRole('button', { name: 'View / edit' }).click();
 await page.getByLabel('Sold (pcs)', { exact: true }).fill('80');
 await page.getByRole('button', { name: 'Save record', exact: true }).click();
 await page.getByText('Record saved.', { exact: true }).waitFor(); assert.equal(records.length, 1); assert.equal(records[0].sales, 200);
 await page.goto('http://localhost:3010/staff/wholesale');
 await page.getByRole('button', { name: 'Buyer contacts', exact: true }).click();
 await page.getByRole('button', { name: 'Add buyer', exact: true }).click();
 await page.getByLabel('Shop / buyer name').fill('Mei Cafe');
 await page.getByLabel('Contact person, phone or email').fill('Mei / 0123456789');
 await page.getByRole('button', { name: 'Save buyer' }).click();
 await page.getByText('Buyer contact saved.').waitFor();
 await page.getByRole('button', { name: 'Orders', exact: true }).click();
 await page.getByRole('button', { name: 'Add wholesale order' }).click();
 await page.getByLabel('Buyer', { exact: true }).selectOption(buyers[0].id);
 await page.getByLabel('Flavour', { exact: true }).fill('Chocolate');
 await page.getByLabel('Quantity (pcs)').fill('100');
 await page.getByLabel('RM / piece').fill('2');
 await page.getByRole('button', { name: '+ Add flavour' }).click();
 await page.getByLabel('Flavour', { exact: true }).nth(1).fill('Matcha');
 await page.getByLabel('Quantity (pcs)').nth(1).fill('50');
 await page.getByLabel('RM / piece').nth(1).fill('2.50');
 await page.getByLabel('Amount received (RM)').fill('100');
 await page.getByRole('button', { name: 'Save record', exact: true }).click();
 await page.getByText('Record saved.', { exact: true }).waitFor();
 assert.equal(records[1].sales, 325); assert.equal(records[1].outstanding, 225);
 await page.getByRole('button', { name: 'View / edit' }).click();
 await page.getByLabel('Amount received (RM)').fill('325');
 await page.getByRole('button', { name: 'Save record', exact: true }).click();
 await page.getByText('Paid in full', { exact: true }).waitFor(); assert.equal(records[1].outstanding, 0);
 await page.goto('http://localhost:3010/staff/dashboard');
 await page.getByText('RM525.00', { exact: true }).waitFor();
 await page.screenshot({ path: 'artifacts/staff-checks/overview-desktop.png', fullPage: true });
 await page.setViewportSize({ width: 390, height: 844 });
 await page.goto('http://localhost:3010/staff/booth');
 await page.getByRole('button', { name: 'Add booth day' }).click();
 assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
 await page.screenshot({ path: 'artifacts/staff-checks/booth-mobile.png', fullPage: true });
 await page.getByRole('button', { name: 'Open staff menu' }).click();
 await page.getByRole('link', { name: 'Wholesale', exact: true }).click();
 await page.getByRole('heading', { name: 'Wholesale', exact: true }).waitFor();
 assert.equal(errors.length, 0, errors.join('\n'));
 console.log('PASS: booth create/edit, buyer create, wholesale flavour pricing and payment update, combined summary, mobile overflow and menu navigation. API data mocked; no live records written.');
 } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
